version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: clearServer.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: fixPrivileges.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: startServer.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: stopServer.sh
      timeout: 300
      runas: ec2-user