management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  application:
    name: Task-API
    description: Simple Task API

server:
  port: 8081

spring:
  profiles:
    active: local