#!groovy

def masterLib = evaluate readTrusted("Jenkins/Pipeline/master.groovy")

pipeline {
    agent any

     environment {
         String API_UPLOAD_BUCKET = "api-bucket"
         String API_BUCKET_KEY = "api"
         String TERRAFORM_VERSION = "1.4.6"
     }

    stages{
        masterLib.runPipeline()
    }

    post {
        // Clean after build
        always {
            echo "Cleaning workspace"
            cleanWs()
        }
    }
}