#! groovy

def commonLib = evaluate readTrusted("Jenkins/Pipeline/common.groovy")
def terraformLib = evaluate readTrusted("Jenkins/Pipeline/terraform.groovy")
def lambdasLib = evaluate readTrusted("Jenkins/Pipeline/lambdas.groovy")
def buildAPILib = evaluate readTrusted("Jenkins/Pipeline/buildAPI.groovy")
def storageLib = evaluate readTrusted("Jenkins/Pipeline/storage.groovy")
def loggerLib = evaluate readTrusted("Jenkins/Pipeline/logger.groovy")
def changeTicketLib = evaluate readTrusted("Jenkins/Pipeline/changeTicket.groovy")
def codedeployLib = evaluate readTrusted("Jenkins/Pipeline/codedeploy.groovy")
def inputLib = evaluate readTrusted("Jenkins/Pipeline/input.groovy")

String appFolder
String backendBucket
String awsRegion
String pipelineAction
String stateTable
String cloudEnv
String ticket

pipeline {
    agent {
        dockerfile {
            filename "Jenkins/Agents/Dockerfile"
        }
    }

    environment {
        String BUCKET_PREFIX = "taskapi-storage-bucket-"
        String DYNAMO_TABLE_PREFIX = "state-lock-table-"
    }

    parameters {
        choice(name: "APP_FOLDER", choices: ["core-resources", "lambdas", "database", "api", "codedeploy"], description: "Folder where pipeline actions should run")
        choice(name: "PIPELINE_ACTION", choices: ["test", "lambdas", "deploy-api", "build-and-deploy-api", "init-and-plan", "apply", "destroy"], description: "Pipeline deploy action")
        choice(name: "CLOUD_ENVIRONMENT", choices: ["dev", "test", "prod"], description: "Deployment cloud environment")
        choice(name: "AWS_REGION", choices: ["us-east-1", "us-east-2", "us-west-1", "ap-southeast-3"], description: "AWS Region to deploy resources and app")
    }

    stages {
        stage("Check Agent") {
            steps {
                script {
                    try {
                        sh """
                            terraform --version
                            gradle --version
                            aws --version
                        """
                    } catch (err) {
                        echo "$err installing Terraform or Gradle in Docker"
                        loggerLib.errorBanner("Terraform or Gradle is not installed. Please check the Dockerfile")
                    }
                }
            }
        }

        stage("Set Variables") {
            steps {
                script {
                    pipelineAction = params.PIPELINE_ACTION
                    awsRegion = params.AWS_REGION
                    appFolder = params.APP_FOLDER
                    cloudEnv = params.CLOUD_ENVIRONMENT

                    backendBucket = commonLib.getBucketName(awsRegion)
                    stateTable = commonLib.getDynamoDBStateTableName(awsRegion)

                    echo "App Folder: $appFolder"
                    echo "Backend State and storage bucket: $backendBucket"
                    echo "DynamoDB state table Name: $stateTable"
                    echo "Current AWS Region: $awsRegion"
                    echo "Cloud Environment $cloudEnv"

                    loggerLib.echoBanner(" \tPipeline Variables set\n \tappFolder: $appFolder\n \tregion: $awsRegion\n \tbackend bucket $backendBucket\n")
                }
            }
        }

        stage("Run API Tests") {
             when {
                expression {
                    return pipelineAction == "test" || pipelineAction == "deploy-api" || pipelineAction == "build-and-deploy-api"
                }
            }
            steps {
                script {
                    timeout(time: 15, unit: "MINUTES") {
                        buildAPILib.runAPITests()
                    }
                }
            }
        }

        stage("Configure AWS Environment") {
            steps {
                script {
                    commonLib.configureAWSProfile(awsRegion)
                }
            }
        }

        stage("Code Deploy") {
            when {
                expression {
                    return pipelineAction == "codedeploy"
                }
            }
            steps {
                script {
                    codedeployLib.getLatestEnvFileName()
                }
            }
        }
         stage("Push API to S3") {
             when {
                expression {
                    return pipelineAction == "test" || pipelineAction == "deploy-api" || pipelineAction == "build-and-deploy-api"
                }
            }
            steps {
                script {
                    storageLib.zipAndPushAPIToS3(backendBucket)
                }
            }
        }

        stage("Build Lambda Environment") {
            when {
                expression {
                    return appFolder == "lambdas"
                }
            }
            steps {
                script {
                    lambdasLib.buildPythonEnvironment()
                }
            }
        }

        stage("Submit change ticket"){
            when {
                expression {
                    return cloudEnv == "prod"
                }
            }

            steps {
                script {
                    timeout(time: 15, unit: "MINUTES") {
                        ticket = changeTicketLib.submitChangeTicket()
                    }
                }
            }
        }

        stage("Init and Plan") {
            when {
                expression {
                    return pipelineAction != "test" && pipelineAction != "deploy-api" && appFolder != "src"
                }
            }

            steps {
                script {
                    terraformLib.terraformInit(backendBucket, appFolder, cloudEnv, awsRegion, stateTable)
                    terraformLib.terraformPlan(appFolder, awsRegion, cloudEnv)
                }
            }
        }

        stage("Apply") {
            when {
                expression {
                    return pipelineAction == "apply"
                }
            }

            steps {
                script {
                    if (cloudEnv == "prod") {
                        echo "Change ticket $ticket"
                        if (ticket == null || ticket == "") {
                            throw new Exception("Change Ticket can not be empty when applying to production.")
                        }
                        storageLib.pushTerraformPlanToS3(bucketName, appFolder, ticket)
                    } else {
                        storageLib.pushTerraformPlanToS3(bucketName, appFolder)
                    }

                    terraformLib.terraformApply(appFolder, awsRegion, cloudEnv)
                }
            }
        }

        stage("Destroy") {
            when {
                expression {
                    return pipelineAction == "destroy"
                }
            }

            steps {
                script {
                    terraformLib.terraformDestroy(appFolder, awsRegion, cloudEnv)
                }
            }
        }

        stage("Build API Environment") {
            when {
                expression {
                    return pipelineAction == "deploy-api" || pipelineAction == "build-and-deploy-api"
                }
            }

            steps {
                script {
                     if (cloudEnv == "prod") {
                        echo "Change ticket $ticket"
                        if (ticket == null || ticket == "") {
                            throw new Exception("Change Ticket can not be empty when applying to production.")
                        }
                    }

                    if (awsRegion != "us-east-1") {
                        storageLib.getAPIEnvFileFromUSEast1Bucket(awsRegion)
                    }
                    String groups = codedeployLib.getCodeDeployGroupsNames(awsRegion)

                    storageLib.getAPIEnvFile(backendBucket)

                    String message = "Would you like to deploy to all cloud environments?"

                    def input = inputLib.getInput(message, "Deploy to All Regions", message, ["yes", "no"])

                    if (input == "yes") {
                        echo "Input to all regions"
                        codedeployLib.deployToAllEnvironments(awsRegion)
                    }else {
                        codedeployLib.startCodeDeploy(backendBucket, awsRegion, cloudEnv)
                    }
                }
            }
        }
    }

    post {
        // Clean after build
        always {
            echo "Cleaning workspace"
            cleanWs()
        }
    }
}